Tong/move to pnpm (#310)
* chore(build): move to pnpm

* chore(build): add preinstall check

* chore(build): update syncpackrc.json

* chore(build): update lock file

* chore(build): replace npx with pnpm exec

* chore(build): use NODE_OPTIONS

* chore(build): add missing cosmjs-types

* chore(build): dedupe cosmjs-types version

diff --git a/.github/workflows/package-release.yml b/.github/workflows/package-release.yml
--- a/.github/workflows/package-release.yml
+++ b/.github/workflows/package-release.yml
@@ -23,30 +23,33 @@ jobs:
         with:
           node-version: '24.2.0'
 
+      - name: Install Corepack
+        run: npm install -g corepack && corepack enable
+
       - name: Install dependencies
-        run: npm ci
+        run: pnpm install --frozen-lockfile
 
       - name: Single Version Policy
         run: |-
           # Exit immediately if any command in the script fails
           set -e
 
-          if npx syncpack list-mismatches; then
+          if pnpm exec syncpack list-mismatches; then
             echo "✅ Dependency versions are aligned"
           else
             # Add an annotation to the Checks tab with a helpful hint
-            echo "::error title=Dependency mismatch::Run 'npx syncpack list-mismatches' locally (and 'npx syncpack fix-mismatches' to auto-fix)." >&2
+            echo "::error title=Dependency mismatch::Run 'pnpm exec syncpack list-mismatches' locally (and 'pnpm exec syncpack fix-mismatches' to auto-fix)." >&2
             exit 1
           fi
 
       - name: Build all
-        run: npx nx run-many --target=build --all
+        run: pnpm exec nx run-many --target=build --all
 
       - name: Lint all
-        run: npx nx run-many --target=lint --all
+        run: pnpm exec nx run-many --target=lint --all
 
       - name: Test all
-        run: npx nx run-many --target=test --all
+        run: pnpm exec nx run-many --target=test --all
 
 
 
@@ -54,8 +57,8 @@ jobs:
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
-          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
-          npm run ci:release
+          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
+          pnpm run ci:release
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
diff --git a/.github/workflows/verify.yml b/.github/workflows/verify.yml
--- a/.github/workflows/verify.yml
+++ b/.github/workflows/verify.yml
@@ -19,27 +19,30 @@ jobs:
         with:
           node-version: '24.2.0'
 
+      - name: Install Corepack
+        run: npm install -g corepack && corepack enable
+
       - name: Install dependencies
-        run: npm ci --verbose
+        run: pnpm install --frozen-lockfile
 
       - name: Single Version Policy
         run: |-
           # Exit immediately if any command in the script fails
           set -e
 
-          if npx syncpack list-mismatches; then
+          if pnpm exec syncpack list-mismatches; then
             echo "✅ Dependency versions are aligned"
           else
             # Add an annotation to the Checks tab with a helpful hint
-            echo "::error title=Dependency mismatch::Run 'npx syncpack list-mismatches' locally (and 'npx syncpack fix-mismatches' to auto-fix)." >&2
+            echo "::error title=Dependency mismatch::Run 'pnpm exec syncpack list-mismatches' locally (and 'pnpm exec syncpack fix-mismatches' to auto-fix)." >&2
             exit 1
           fi
 
       - name: Build affected
-        run: npx nx affected --target=build --base=origin/main --verbose
+        run: pnpm exec nx affected --target=build --base=origin/main --verbose
 
       - name: Lint affected
-        run: npx nx affected --target=lint --base=origin/main --verbose
+        run: pnpm exec nx affected --target=lint --base=origin/main --verbose
 
       - name: Test affected
-        run: npx nx affected --target=test --base=origin/main --verbose
+        run: pnpm exec nx affected --target=test --base=origin/main --verbose
