chore(build): enforce single version policy (#81)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -26,6 +26,19 @@ jobs:
       - name: Install dependencies
         run: npm install
 
+      - name: Single Version Policy
+        run: |-
+          # Exit immediately if any command in the script fails
+          set -e
+
+          if npx syncpack list-mismatches; then
+            echo "✅ Dependency versions are aligned"
+          else
+            # Add an annotation to the Checks tab with a helpful hint
+            echo "::error title=Dependency mismatch::Run 'npx syncpack list-mismatches' locally (and 'npx syncpack fix-mismatches' to auto-fix)." >&2
+            exit 1
+          fi
+
       - name: Lint all
         run: npx nx run-many --target=lint --all
 
diff --git a/.github/workflows/verify.yml b/.github/workflows/verify.yml
--- a/.github/workflows/verify.yml
+++ b/.github/workflows/verify.yml
@@ -22,6 +22,19 @@ jobs:
       - name: Install dependencies
         run: npm ci --verbose
 
+      - name: Single Version Policy
+        run: |-
+          # Exit immediately if any command in the script fails
+          set -e
+
+          if npx syncpack list-mismatches; then
+            echo "✅ Dependency versions are aligned"
+          else
+            # Add an annotation to the Checks tab with a helpful hint
+            echo "::error title=Dependency mismatch::Run 'npx syncpack list-mismatches' locally (and 'npx syncpack fix-mismatches' to auto-fix)." >&2
+            exit 1
+          fi
+
       - name: Lint affected
         run: npx nx affected --target=lint --base=origin/main --verbose
 
